export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const SEARCH_PROJECTS_BY_TAG = "SEARCH_PROJECTS_BY_TAG";
export const SEARCH_PROJECTS_BY_KEYWORD = "SEARCH_PROJECTS_BY_KEYWORD";
export const SEARCH_PROJECTS_BY_CATEGORY = "SEARCH_PROJECTS_BY_CATEGORY";


export const START_FETCH_PROJECT_DETAIL = "START_FETCH_PROJECT_DETAIL";
export const SUCCESS_FETCH_PROJECT_DETAIL = "SUCCESS_FETCH_PROJECT_DETAIL";
export const FAIL_FETCH_PROJECT_DETAIL = "FETCH_PROJECT_DETAIL"


export const START_FETCH_ALL_PROJECTS = "START_FETCH_ALL_PROJECTS";
export const SUCCESS_FETCH_ALL_PROJECTS = "SUCCESS_FETCH_ALL_PROJECTS";
export const FAIL_FETCH_ALL_PROJECTS = "FAIL_FETCH_ALL_PROJECTS";



export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const LOG_OUT = "LOG_OUT";
export const GET_USER_DETAIL ="GET_USER_DETAIL";