export const FILTER_BY_HACKATHON_TITLE = 'FILTER_BY_HACKATHON_TITLE';
export const FILTER_BY_POPULAR_TAGS = 'FILTER_BY_POPULAR_TAGS';
export const FILTER_BY_STATUS = 'FILTER_BY_STATUS';
export const FILTER_BY_HOST = 'FILTER_BY_HOST';