export const myProjects = [
    // {
    //     id: 1,
    //     key: 1,
    //     name: "Cooking Food",
    //     img: "https://thumbor.thedailymeal.com/hsnb0THPeTK9DWNdEH3miTs6DrU=//https://www.thedailymeal.com/sites/default/files/2020/05/21/HERO_Best_podcast_GettyImages-1173531336.jpg",
    //     desc: "Home Cooking was conceived as a way to help people figure out what to cook during quarantine",
    //     gmail: "chef@gmail.com",
    //     address: "USA",
    //     date: 'Mar 15, 2022',
    //     time: "8:30",
    //     tags: ["Food", "Social Good"],
    //     status: "ongoing",
    //     viewers: 7,
    //     likes: 8,
    //     comments: 10,
    //     categories: ['Project Showcase'],
    //     creator: 'thao',
    //     progress: 'done',

    // },
    {
        id: 2,
        name: 'Learn basic JS',
        img: 'https://thietkewebdalat.net/blog/wp-content/uploads/2020/04/javascript-la-gi.jpg',
        date: 'Mar 15, 2022',
        status: 'ongoing',
        desc: 'JavaScript (JS) is a lightweight, interpreted, or just-in-time compiled programming language with first-class functions',
        viewers: 7,
        likes: 5,
        comments: 15,
        tags: ["Javascript"],
        categories: ['Currently Fundraising'],
        creator: 'thao',
        progress: 'done',
        isWinning: false

    },
    {
        id: 3,
        name: 'Learn basic React Native',
        img: 'https://blog.haposoft.com/content/images/2020/10/react_native_vs_native_apps.png',
        date: 'Jul 10, 2022',
        status: 'coming-soon',
        desc: 'React Native lets you create truly native apps and doesnt compromise your users experiences. It provides a core set of platform agnostic native components',
        viewers: 9,
        likes: 3,
        comments: 6,
        tags: ['React Native'],
        categories: ['Project Showcase'],
        creator: 'thao',
        progress: 'draft',
        isWinning: true
    },
]

